title: Jere Koski
logo: cvExtra2.png
description: I am a software developer specializing in Full Stack development and Artificial Intelligence. I hold a master's degree from Tampere University.

My work history is varied, encompassing diverse environments, technologies, and projects, from AI projects utilizing neural networks, Azure AI, and ChatGPT to web projects developing frontend and backend development using JavaScript, TypeScript, Java, and SQL.
show_downloads: true
theme: jekyll-theme-minimal
